package(default_visibility = ["//visibility:public"])

py_binary(
    name = "sample_tf_graph",
    srcs = ["sample_tf_graph.py"],
    main = "sample_tf_graph.py",
)

filegroup(
    name = "tensorflow_inception_graph",
    srcs = [
        "tensorflow_inception_graph.pb",
    ],
)
